### ISSUE TITLE
Please review and pull 3 little changes

### ISSUE THREAD

**Issue by nephros** [sh6668/gmLocate#1]
Hi,

I have done some improvement work over at the below location.
If you like it, please comment and/or pull in the changes.

https://gitlab.com/nephros/gmlocate/-/compare/master...for-upstream

Sorry for making a ~~fuzz~~ issue about is, I don't know how to have GitLab interoperate with Microsoft GitHub wrt. PRs/MRs, and want to avoid working with MS GH where possible.

**Comment by sh6668** [comment]
Hi,

thanks
looks good to me.

**Comment by sh6668** [comment]
hi

the work is done.

Maybe i switch to gitlab.
avoiding MS is a good idea;-)
